[tool.ruff]
line-length = 140
indent-width = 4
exclude = [
    '.bzr',
    '.direnv',
    '.eggs',
    '.git',
    '.git-rewrite',
    '.hg',
    '.ipynb_checkpoints',
    '.mypy_cache',
    '.nox',
    '.pants.d',
    '.pyenv',
    '.pytest_cache',
    '.pytype',
    '.ruff_cache',
    '.svn',
    '.tox',
    '.venv',
    '.vscode',
    '__pypackages__',
    '_build',
    'buck-out',
    'build',
    'dist',
    'node_modules',
    'site-packages',
    'venv',
    'deps',
    'binaries',
    '__pycache__'
]
[tool.ruff.lint]
select = ['C901', 'E', 'W', 'F', 'RET505', 'I001', 'B034', 'EXE001', 'N', 'UP032', 'FA']
ignore = []
mccabe = { max-complexity = 14 }

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.pylint]
ignore=[
    '.bzr',
    '.direnv',
    '.eggs',
    '.git',
    '.git-rewrite',
    '.hg',
    '.ipynb_checkpoints',
    '.mypy_cache',
    '.nox',
    '.pants.d',
    '.pyenv',
    '.pytest_cache',
    '.pytype',
    '.ruff_cache',
    '.svn',
    '.tox',
    '.venv',
    '.vscode',
    '__pypackages__',
    '_build',
    'buck-out',
    'build',
    'dist',
    'node_modules',
    'site-packages',
    'venv',
    'deps',
    'binaries',
    '__pycache__'
]
recursive=true
load-plugins = ["pylint_protobuf"]
enable = ["useless-suppression"]

[tool.pylint.format]
max-line-length=140
max-module-lines=1000

[tool.pylint.messages_control]
disable=['wrong-import-order',
        'missing-module-docstring',
        'missing-class-docstring',
        'missing-function-docstring',
        'duplicate-code']

[tool.mypy]
strict = true
allow_untyped_calls = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = "someip.*"
ignore_missing_imports = true
